/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsyatem;

import java.awt.Image;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.JFrame;

/**
 *
 * @author hp
 */


public class AddPatient extends javax.swing.JFrame {

    /**
     * Creates new form AddPatient
     */
  
    
    public AddPatient() {
        initComponents();
        
        curdateTime();
        
         Icon i = lblpatient.getIcon();
        
        ImageIcon icon = (ImageIcon)i;
        
        Image image;
        image = icon.getImage().getScaledInstance(lblpatient.getWidth(), lblpatient.getHeight(), Image.SCALE_SMOOTH);
        
        lblpatient.setIcon(new ImageIcon(image));
        
        Random r = new Random();
        
        int pid = r.nextInt(1000);
        
        lblpid.setText(String.valueOf(pid));
          
    }
    
   public void curdateTime()
    {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("YYYY/MM/dd HH:mm:ss");
        
        LocalDateTime now = LocalDateTime.now();
        
        lbldatetime.setText(dtf.format(now));
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        lblheader = new javax.swing.JLabel();
        lblheader1 = new javax.swing.JLabel();
        lblheader2 = new javax.swing.JLabel();
        lblheader3 = new javax.swing.JLabel();
        lblheader4 = new javax.swing.JLabel();
        lblheader5 = new javax.swing.JLabel();
        lblheader6 = new javax.swing.JLabel();
        lblheader7 = new javax.swing.JLabel();
        txtpname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtdeposite = new javax.swing.JTextField();
        rbtmale = new javax.swing.JRadioButton();
        rbtfemale = new javax.swing.JRadioButton();
        rbtother = new javax.swing.JRadioButton();
        cmbroom = new javax.swing.JComboBox<>();
        btnaddpatient = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        lblpatient = new javax.swing.JLabel();
        lbldatetime = new javax.swing.JLabel();
        lblheader8 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        lblheader9 = new javax.swing.JLabel();
        txtdiseases = new javax.swing.JTextField();
        lblpid = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Patient");
        setLocation(new java.awt.Point(250, 70));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 4));

        lblheader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblheader.setForeground(new java.awt.Color(255, 255, 204));
        lblheader.setText("Add New Patient Information.");

        lblheader1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblheader1.setForeground(new java.awt.Color(255, 255, 204));
        lblheader1.setText("Patient Name :");

        lblheader2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblheader2.setForeground(new java.awt.Color(255, 255, 204));
        lblheader2.setText("Patient Id :");

        lblheader3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblheader3.setForeground(new java.awt.Color(255, 255, 204));
        lblheader3.setText("Gender :");

        lblheader4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblheader4.setForeground(new java.awt.Color(255, 255, 204));
        lblheader4.setText("Room No :");

        lblheader5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblheader5.setForeground(new java.awt.Color(255, 255, 204));
        lblheader5.setText("Mobile No :");

        lblheader6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblheader6.setForeground(new java.awt.Color(255, 255, 204));
        lblheader6.setText("Diseases :");

        lblheader7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblheader7.setForeground(new java.awt.Color(255, 255, 204));
        lblheader7.setText("Date :");

        txtpname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtdeposite.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        buttonGroup1.add(rbtmale);
        rbtmale.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtmale.setForeground(new java.awt.Color(255, 255, 204));
        rbtmale.setText("Male");
        rbtmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtmaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtfemale);
        rbtfemale.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtfemale.setForeground(new java.awt.Color(255, 255, 204));
        rbtfemale.setText("Female");
        rbtfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtfemaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtother);
        rbtother.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtother.setForeground(new java.awt.Color(255, 255, 204));
        rbtother.setText("Other");
        rbtother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtotherActionPerformed(evt);
            }
        });

        cmbroom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbroom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "201", "202", "203", "301", "302", "303" }));
        cmbroom.setSelectedIndex(-1);
        cmbroom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbroomItemStateChanged(evt);
            }
        });
        cmbroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbroomActionPerformed(evt);
            }
        });

        btnaddpatient.setBackground(new java.awt.Color(0, 0, 0));
        btnaddpatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnaddpatient.setForeground(new java.awt.Color(255, 255, 204));
        btnaddpatient.setText("Add Patient");
        btnaddpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddpatientActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(0, 0, 0));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 204));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        lblpatient.setForeground(new java.awt.Color(255, 255, 204));
        lblpatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsyatem/Icon/doctor-visit.png"))); // NOI18N
        lblpatient.setText("jLabel1");

        lbldatetime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbldatetime.setForeground(new java.awt.Color(255, 255, 204));

        lblheader8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblheader8.setForeground(new java.awt.Color(255, 255, 204));
        lblheader8.setText("Age :");

        txtmobile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblheader9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblheader9.setForeground(new java.awt.Color(255, 255, 204));
        lblheader9.setText("Deposite :");

        txtdiseases.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtdiseases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiseasesActionPerformed(evt);
            }
        });

        lblpid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblpid.setForeground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnaddpatient)
                        .addGap(188, 188, 188)
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(lblheader)))
                .addContainerGap(448, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblheader7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblheader6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblheader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblheader3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblheader5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblheader4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblheader8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblheader9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblpid, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbldatetime, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbroom, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtmale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtfemale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtother, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtdiseases, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtmobile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                .addComponent(txtpname, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtage, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtdeposite, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(lblpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(lblheader2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(808, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblheader)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(lblpid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblheader8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblheader1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblheader3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rbtmale, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rbtfemale, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rbtother, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblheader5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblheader4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblheader6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdiseases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(lblpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblheader7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lbldatetime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblheader9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtdeposite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 92, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 568, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnaddpatient)
                            .addComponent(btnback))
                        .addGap(26, 26, 26))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(lblheader2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(538, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtmaleActionPerformed

    private void rbtfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtfemaleActionPerformed

    private void rbtotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtotherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtotherActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
       
        
       this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnaddpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddpatientActionPerformed
        
     
        if("".equals(txtpname.getText()) || "".equals(txtage.getText()) || "".equals(txtmobile.getText()) || "".equals(txtdiseases.getText()) || "".equals(txtdeposite.getText()))
        {
              JOptionPane.showMessageDialog(rootPane, "Please Enter Values Into Fields.");
        }
        else
        {
        
               String name = txtpname.getText();
               String gender;
       
              if(rbtmale.isSelected())
              {
                  gender="male";
              }
              else if(rbtfemale.isSelected())
              {
                   gender="female";
              } 
              else
              {
                   gender="other";
              }
       
                String age = txtage.getText();
       
                String mobile =txtmobile.getText();
       
                String room = (String) cmbroom.getSelectedItem();
       
                String diseases = txtdiseases.getText();
       
                String dt =  lbldatetime.getText();
       
                String deposite = txtdeposite.getText();       
        
            try {
                    DBConnect DBCon =  new DBConnect();
             
                    String qry = "insert into patient values('"+lblpid.getText()+"','"+name+"','"+gender+"','"+age+"','"+mobile+"','"+diseases+"','"+room+"','"+dt+"','"+deposite+"')";
            
                    String qry1 = "update room set availability='Occupied' where room_no='"+room+"'";
            
                    int rs = DBConnect.stmt.executeUpdate(qry);
            
                    int rs1 = DBConnect.stmt.executeUpdate(qry1);
                    
                    
                          if(rs>0)
                          {
                                JOptionPane.showMessageDialog(null, "Record Added Successfully..");
                                this.setVisible(false);    
                          }
                           else
                          {
                           JOptionPane.showMessageDialog(null, "Something is Wrong..!");
                          }  
            
                } catch (ClassNotFoundException | SQLException ex) {
                      Logger.getLogger(AddPatient.class.getName()).log(Level.SEVERE, null, ex);
                       JOptionPane.showMessageDialog(null, ex);
           }
        }
    }//GEN-LAST:event_btnaddpatientActionPerformed

    private void txtdiseasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiseasesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiseasesActionPerformed

    private void cmbroomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbroomItemStateChanged
           
    }//GEN-LAST:event_cmbroomItemStateChanged

    private void cmbroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbroomActionPerformed
         String room_no  = (String) cmbroom.getSelectedItem();
        
        String qry = "select room_no from patient where room_no='"+room_no+"'";
        
        ResultSet rs;
        try {
            
            DBConnect obj = new DBConnect();
            rs = DBConnect.stmt.executeQuery(qry);
            
              if(rs.next())
              {
                    JOptionPane.showMessageDialog(null, "Selected Room is Not Available Now.");
                    
              }
        } catch (SQLException ex) {
            Logger.getLogger(AddPatient.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddPatient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbroomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddpatient;
    private javax.swing.JButton btnback;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbroom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbldatetime;
    private javax.swing.JLabel lblheader;
    private javax.swing.JLabel lblheader1;
    private javax.swing.JLabel lblheader2;
    private javax.swing.JLabel lblheader3;
    private javax.swing.JLabel lblheader4;
    private javax.swing.JLabel lblheader5;
    private javax.swing.JLabel lblheader6;
    private javax.swing.JLabel lblheader7;
    private javax.swing.JLabel lblheader8;
    private javax.swing.JLabel lblheader9;
    private javax.swing.JLabel lblpatient;
    private javax.swing.JLabel lblpid;
    private javax.swing.JRadioButton rbtfemale;
    private javax.swing.JRadioButton rbtmale;
    private javax.swing.JRadioButton rbtother;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtdeposite;
    private javax.swing.JTextField txtdiseases;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtpname;
    // End of variables declaration//GEN-END:variables
}
