/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
package hospitalmanagementsyatem;


import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        
        
       //jPanel1.setBackground(new Color(0,128,128));
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
         Icon i = lblimage.getIcon();
        
        ImageIcon icon = (ImageIcon)i;
        
        Image image;
        image = icon.getImage().getScaledInstance(lblimage.getWidth(), lblimage.getHeight(), Image.SCALE_SMOOTH);
        
        lblimage.setIcon(new ImageIcon(image));
        
        Image titleIcon = Toolkit.getDefaultToolkit().getImage("E:\\man\\my project\\HospitalManagementSyatem\\src\\hospitalmanagementsyatem\\Icon\\icons8-hospital-64.png");
        this.setIconImage(titleIcon);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnadddoctor = new javax.swing.JButton();
        btnaddpatient = new javax.swing.JButton();
        btnroominfo = new javax.swing.JButton();
        btnpatientinfo = new javax.swing.JButton();
        btndischarge = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnsearchpatient = new javax.swing.JButton();
        btndoctorsinfo = new javax.swing.JButton();
        btngenopd = new javax.swing.JButton();
        btngenopdinfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setLocation(new java.awt.Point(-5, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1950, 1090));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Welcome To Appolo Hospital");

        btnadddoctor.setBackground(new java.awt.Color(255, 255, 204));
        btnadddoctor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnadddoctor.setText("Add Doctor");
        btnadddoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadddoctorActionPerformed(evt);
            }
        });

        btnaddpatient.setBackground(new java.awt.Color(255, 255, 204));
        btnaddpatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnaddpatient.setText("Add Patient");
        btnaddpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddpatientActionPerformed(evt);
            }
        });

        btnroominfo.setBackground(new java.awt.Color(255, 255, 204));
        btnroominfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnroominfo.setText("Room Info");
        btnroominfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroominfoActionPerformed(evt);
            }
        });

        btnpatientinfo.setBackground(new java.awt.Color(255, 255, 204));
        btnpatientinfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnpatientinfo.setText("IPD Patients Info");
        btnpatientinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientinfoActionPerformed(evt);
            }
        });

        btndischarge.setBackground(new java.awt.Color(255, 255, 204));
        btndischarge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndischarge.setText("Discharge Patient");
        btndischarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndischargeActionPerformed(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(255, 255, 204));
        btnlogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogout.setText("Log Out");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsyatem/Icon/clinic.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementsyatem/Icon/icons8-hospital-64.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        btnsearchpatient.setBackground(new java.awt.Color(255, 255, 204));
        btnsearchpatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsearchpatient.setText("Search Patient");
        btnsearchpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchpatientActionPerformed(evt);
            }
        });

        btndoctorsinfo.setBackground(new java.awt.Color(255, 255, 204));
        btndoctorsinfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndoctorsinfo.setText("Doctors Info");
        btndoctorsinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoctorsinfoActionPerformed(evt);
            }
        });

        btngenopd.setBackground(new java.awt.Color(255, 255, 204));
        btngenopd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btngenopd.setText("General OPD");
        btngenopd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenopdActionPerformed(evt);
            }
        });

        btngenopdinfo.setBackground(new java.awt.Color(255, 255, 204));
        btngenopdinfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btngenopdinfo.setText("General OPD Info");
        btngenopdinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenopdinfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btngenopd)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btngenopdinfo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnadddoctor)
                                .addGap(79, 79, 79)
                                .addComponent(btnroominfo)
                                .addGap(72, 72, 72)
                                .addComponent(btnpatientinfo)
                                .addGap(78, 78, 78)
                                .addComponent(btndischarge)
                                .addGap(58, 58, 58)
                                .addComponent(btnsearchpatient)))))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndoctorsinfo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnlogout)))
                .addContainerGap(406, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(btnaddpatient)
                    .addContainerGap(1758, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnlogout)
                                .addComponent(jLabel2)))
                        .addGap(9, 9, 9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadddoctor)
                    .addComponent(btnroominfo)
                    .addComponent(btnpatientinfo)
                    .addComponent(btndischarge)
                    .addComponent(btnsearchpatient)
                    .addComponent(btndoctorsinfo))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngenopd)
                    .addComponent(btngenopdinfo))
                .addContainerGap(798, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(btnaddpatient)
                    .addContainerGap(854, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnadddoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadddoctorActionPerformed
        
        
        AddDoctor obj = new AddDoctor();
        obj.setVisible(true);
        
    }//GEN-LAST:event_btnadddoctorActionPerformed

    private void btnaddpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddpatientActionPerformed

      
       AddPatient obj = new AddPatient();
       
       obj.setVisible(true);
        
    }//GEN-LAST:event_btnaddpatientActionPerformed

    private void btnroominfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroominfoActionPerformed
        
        RoomInfo obj = new RoomInfo();
        obj.setVisible(true);
    }//GEN-LAST:event_btnroominfoActionPerformed

    private void btnpatientinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientinfoActionPerformed
        
        PatientInfo obj = new PatientInfo();
        
        obj.setVisible(true);
    }//GEN-LAST:event_btnpatientinfoActionPerformed

    private void btndischargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndischargeActionPerformed
        try {
            DischargePAtient obj = new DischargePAtient();
            obj.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
               
    }//GEN-LAST:event_btndischargeActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        
        this.dispose();
        LoginPage obj = new LoginPage();
        obj.setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnsearchpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchpatientActionPerformed
        // TODO add your handling code here:
        
        SearchPatient obj = new SearchPatient();
        
        obj.setVisible(true);
    }//GEN-LAST:event_btnsearchpatientActionPerformed

    private void btndoctorsinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoctorsinfoActionPerformed
        // TODO add your handling code here:
        DoctorInformation obj = new DoctorInformation();
       
        obj.setVisible(true);
    }//GEN-LAST:event_btndoctorsinfoActionPerformed

    private void btngenopdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenopdActionPerformed
        
        GeneralOpd obj = new GeneralOpd();
        obj.setVisible(true);
         
    }//GEN-LAST:event_btngenopdActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
       
    }//GEN-LAST:event_formWindowActivated

    private void btngenopdinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenopdinfoActionPerformed
       
         OPDInfo obj = new OPDInfo();
         obj.setVisible(true);
    }//GEN-LAST:event_btngenopdinfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadddoctor;
    private javax.swing.JButton btnaddpatient;
    private javax.swing.JButton btndischarge;
    private javax.swing.JButton btndoctorsinfo;
    private javax.swing.JButton btngenopd;
    private javax.swing.JButton btngenopdinfo;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnpatientinfo;
    private javax.swing.JButton btnroominfo;
    private javax.swing.JButton btnsearchpatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblimage;
    // End of variables declaration//GEN-END:variables
}
